### ISSUE TITLE
Zookeper status on yellow 

### ISSUE THREAD

**Issue by daafgo** [apache/lucene-solr-operator#171]
**Describe the bug**
After deploying the solr operator using the zookeper, everything goes fine but I get this error in the solr admin panel
**To Reproduce**
this it's my yaml file
apiVersion: solr.bloomberg.com/v1beta1
kind: SolrCloud
metadata:
  name: solr-cloud-rp
  namespace: solr-operator
spec:
  replicas: 4
  solrImage:
    tag: 8.7.0
  dataStorage:
    persistent:
      pvcTemplate:
        spec:
          storageClassName: "rook-ceph-block"
          resources:
            requests:
              storage: "10Gi"
  zookeeperRef:
    provided:
      chroot: "/this/will/be/auto/created"
      persistence:
        spec:
          storageClassName: "rook-ceph-block"
          resources:
            requests:
              storage: "5Gi"
    replicas: 3      

**Screenshots**
![image](https://user-images.githubusercontent.com/2371762/104027569-7cd6fe00-51bf-11eb-8921-6850061d21bc.png)

**Comment by HoustonPutman** [comment]
This is due to the Zookeeper Operator unfortunately changing the way that their ZK nodes address themselves. Whenever we are able to update the Zookeeper Operator dependency, we can fix this issue.

However this is not a bug in Solr, just a warning. Everything will be working just fine, despite the "errors".
