### ISSUE TITLE
extensions/v1beta1 Ingress is deprecated

### ISSUE THREAD

**Issue by madrob** [apache/lucene-solr-operator#214]
After deploying a cluster using this operator, I wanted to get the Ingress, but the one we currently use is deprecated.

```$ k get ing
Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress```

**Comment by HoustonPutman** [comment]
We should go ahead and make sure that all dependent resources are up to date with the most recent version.

**Comment by HoustonPutman** [comment]
So `networking.k8s.io/v1 Ingress` is stable starting in Kubernetes 1.19. Since 1.16 is currently our minimum supported version, we will need to use `networking.k8s.io/v1beta1 Ingress` until 1.19 is our minimum supported version.

I believe `networking.k8s.io/v1beta1` will be around longer than `extensions.k8s.io/v1beta1`, so moving there for now should be safe.
